/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminActivityRouteImport } from './routes/_admin.activity'
import { Route as AdminApprovalsIndexRouteImport } from './routes/_admin.approvals.index'
import { Route as AdminApprovalsIdRouteImport } from './routes/_admin.approvals.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsIndexRoute = AdminApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsIdRoute = AdminApprovalsIdRouteImport.update({
  id: '/approvals/$id',
  path: '/approvals/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof AdminActivityRoute
  '/dashboard': typeof AdminDashboardRoute
  '/approvals/$id': typeof AdminApprovalsIdRoute
  '/approvals/': typeof AdminApprovalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof AdminActivityRoute
  '/dashboard': typeof AdminDashboardRoute
  '/approvals/$id': typeof AdminApprovalsIdRoute
  '/approvals': typeof AdminApprovalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/activity': typeof AdminActivityRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/approvals/$id': typeof AdminApprovalsIdRoute
  '/_admin/approvals/': typeof AdminApprovalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity' | '/dashboard' | '/approvals/$id' | '/approvals/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity' | '/dashboard' | '/approvals/$id' | '/approvals'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/activity'
    | '/_admin/dashboard'
    | '/_admin/approvals/$id'
    | '/_admin/approvals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/activity': {
      id: '/_admin/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/approvals/': {
      id: '/_admin/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AdminApprovalsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/approvals/$id': {
      id: '/_admin/approvals/$id'
      path: '/approvals/$id'
      fullPath: '/approvals/$id'
      preLoaderRoute: typeof AdminApprovalsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminApprovalsIdRoute: typeof AdminApprovalsIdRoute
  AdminApprovalsIndexRoute: typeof AdminApprovalsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminApprovalsIdRoute: AdminApprovalsIdRoute,
  AdminApprovalsIndexRoute: AdminApprovalsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
